#ifndef ADDRESS_MAP_HPP
#define ADDRESS_MAP_HPP


#define CUSTOM_MEMORY_OFFSET 0x40005000u

//Filter Kernel
#define IMG_FILTER_KERNEL_OFFSET 0x00000003u
#define IMG_FILTER_KERNEL_SIZE 36
#define IMG_FILTER_KERNEL_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_FILTER_KERNEL_OFFSET 
#define IMG_FILTER_KERNEL_ADDRESS_HI IMG_FILTER_KERNEL_ADDRESS_LO + IMG_FILTER_KERNEL_SIZE

//Filter Output
#define IMG_FILTER_OUTPUT_OFFSET 0x00000027u
#define IMG_FILTER_OUTPUT_SIZE 1
#define IMG_FILTER_OUTPUT_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_FILTER_OUTPUT_OFFSET 
#define IMG_FILTER_OUTPUT_ADDRESS_HI IMG_FILTER_OUTPUT_ADDRESS_LO + IMG_FILTER_OUTPUT_SIZE

//Sobel Input 0
#define SOBEL_INPUT_0_OFFSET 0x00000028u
#define SOBEL_INPUT_0_SIZE 8
#define SOBEL_INPUT_0_ADDRESS_LO CUSTOM_MEMORY_OFFSET + SOBEL_INPUT_0_OFFSET 
#define SOBEL_INPUT_0_ADDRESS_HI SOBEL_INPUT_0_ADDRESS_LO + SOBEL_INPUT_0_SIZE

//Sobel Input 1
#define SOBEL_INPUT_1_OFFSET 0x00000030u
#define SOBEL_INPUT_1_SIZE 1
#define SOBEL_INPUT_1_ADDRESS_LO CUSTOM_MEMORY_OFFSET + SOBEL_INPUT_1_OFFSET 
#define SOBEL_INPUT_1_ADDRESS_HI SOBEL_INPUT_1_ADDRESS_LO + SOBEL_INPUT_1_SIZE

//Sobel Output 1
#define SOBEL_OUTPUT_OFFSET 0x00000031u
#define SOBEL_OUTPUT_SIZE 4
#define SOBEL_OUTPUT_ADDRESS_LO CUSTOM_MEMORY_OFFSET + SOBEL_OUTPUT_OFFSET 
#define SOBEL_OUTPUT_ADDRESS_HI SOBEL_OUTPUT_ADDRESS_LO + SOBEL_OUTPUT_SIZE

//Img Input
#define IMG_INPUT_OFFSET 0x00000035u
#define IMG_INPUT_SIZE 921600
#define IMG_INPUT_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_INPUT_OFFSET 
#define IMG_INPUT_ADDRESS_HI IMG_INPUT_ADDRESS_LO + IMG_INPUT_SIZE

//Img In Process A
#define IMG_INPROCESS_A_OFFSET 0x0000E135u
#define IMG_INPROCESS_A_SIZE 307200
#define IMG_INPROCESS_A_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_INPROCESS_A_OFFSET 
#define IMG_INPROCESS_A_ADDRESS_HI IMG_INPROCESS_A_ADDRESS_LO + IMG_INPROCESS_A_SIZE

//Img In Process B
#define IMG_INPROCESS_B_OFFSET 0x0012C035u
#define IMG_INPROCESS_B_SIZE 614400
#define IMG_INPROCESS_B_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_INPROCESS_B_OFFSET 
#define IMG_INPROCESS_B_ADDRESS_HI IMG_INPROCESS_B_ADDRESS_LO + IMG_INPROCESS_B_SIZE

//Img In Process C
#define IMG_INPROCESS_C_OFFSET 0x001C2035u
#define IMG_INPROCESS_C_SIZE 614400
#define IMG_INPROCESS_C_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_INPROCESS_C_OFFSET 
#define IMG_INPROCESS_C_ADDRESS_HI IMG_INPROCESS_C_ADDRESS_LO + IMG_INPROCESS_C_SIZE

//Img Compressed
#define IMG_COMPRESSED_OFFSET 0x00258035u
#define IMG_COMPRESSED_SIZE 307200
#define IMG_COMPRESSED_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_COMPRESSED_OFFSET 
#define IMG_COMPRESSED_ADDRESS_HI IMG_COMPRESSED_ADDRESS_LO + IMG_COMPRESSED_SIZE

//Img Compressed
#define IMG_OUTPUT_OFFSET 0x002A3035u
#define IMG_OUTPUT_SIZE 307200
#define IMG_OUTPUT_ADDRESS_LO CUSTOM_MEMORY_OFFSET + IMG_OUTPUT_OFFSET 
#define IMG_OUTPUT_ADDRESS_HI IMG_OUTPUT_ADDRESS_LO + IMG_OUTPUT_SIZE


#endif // ADDRESS_MAP_HPP
