#!/bin/bash

case $1 in
  "save_log")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 IPS_FILTER_LT_EN=1 EDGE_DETECTOR_AT_EN=1 IMG_UNIFICATE_PV_EN=1 IPS_JPG_PV_EN=1 USING_TLM_TB_EN=1 all > output.log
    ;;
  "save_log_no_dbg")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 IPS_FILTER_LT_EN=1 EDGE_DETECTOR_AT_EN=1 IMG_UNIFICATE_PV_EN=1 IPS_JPG_PV_EN=1 USING_TLM_TB_EN=1 DISABLE_ROUTER_DEBUG=1 DISABLE_FILTER_DEBUG=1 DISABLE_MEM_DEBUG=1 DISABLE_RGB_DEBUG=1 DISABLE_SOBEL_DEBUG=1 DISABLE_TB_DEBUG=1 all > output.log
    ;;
  "print_all")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 IPS_FILTER_LT_EN=1 EDGE_DETECTOR_AT_EN=1 IMG_UNIFICATE_PV_EN=1 IPS_JPG_PV_EN=1 USING_TLM_TB_EN=1 print-all
    ;;
  "compile")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 IPS_FILTER_LT_EN=1 EDGE_DETECTOR_AT_EN=1 IMG_UNIFICATE_PV_EN=1 IPS_JPG_PV_EN=1 USING_TLM_TB_EN=1 DISABLE_ROUTER_DEBUG=1 DISABLE_FILTER_DEBUG=1 DISABLE_MEM_DEBUG=1 DISABLE_RGB_DEBUG=1 DISABLE_SOBEL_DEBUG=1 DISABLE_TB_DEBUG=1 compile
    ;;
  "router_tb")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 EDGE_DETECTOR_AT_EN=1 USING_TLM_ROUTER_TB_EN=1 USING_TLM_TB_EN=1 all > output.log
    ;;
  "router_tb")
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 EDGE_DETECTOR_AT_EN=1 USING_TLM_ROUTER_TB_EN=1 USING_TLM_TB_EN=1 all > output.log
    ;;
  *)
    make INCLUDE_OPENCV_PKG=1 RGB2GRAY_PV_EN=1 IPS_FILTER_LT_EN=1 EDGE_DETECTOR_AT_EN=1 IMG_UNIFICATE_PV_EN=1 IPS_JPG_PV_EN=1 USING_TLM_TB_EN=1 DISABLE_ROUTER_DEBUG=1 DISABLE_FILTER_DEBUG=1 DISABLE_MEM_DEBUG=1 DISABLE_RGB_DEBUG=1 DISABLE_SOBEL_DEBUG=1 DISABLE_TB_DEBUG=1 all
    ;;
esac
