// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Filter,hls_ip_2019_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a75ti-ftg256-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.728964,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=11,HLS_SYN_FF=1242,HLS_SYN_LUT=1311,HLS_VERSION=2019_1}" *)

module Filter (
        input_window_0,
        input_window_1,
        input_window_2,
        input_window_3,
        input_window_4,
        input_window_5,
        input_window_6,
        input_window_7,
        input_window_8,
        output_r,
        clk,
        ap_rst
);


input  [7:0] input_window_0;
input  [7:0] input_window_1;
input  [7:0] input_window_2;
input  [7:0] input_window_3;
input  [7:0] input_window_4;
input  [7:0] input_window_5;
input  [7:0] input_window_6;
input  [7:0] input_window_7;
input  [7:0] input_window_8;
output  [7:0] output_r;
input   clk;
input   ap_rst;

reg[7:0] output_r;

wire   [7:0] grp_Filter_filter_fu_72_output_r;
wire    grp_Filter_filter_fu_72_output_r_ap_vld;
wire   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;

Filter_filter grp_Filter_filter_fu_72(
    .ap_clk(clk),
    .ap_rst(ap_rst),
    .input_window_0(input_window_0),
    .input_window_1(input_window_1),
    .input_window_2(input_window_2),
    .input_window_3(input_window_3),
    .input_window_4(input_window_4),
    .input_window_5(input_window_5),
    .input_window_6(input_window_6),
    .input_window_7(input_window_7),
    .input_window_8(input_window_8),
    .output_r(grp_Filter_filter_fu_72_output_r),
    .output_r_ap_vld(grp_Filter_filter_fu_72_output_r_ap_vld)
);

always @ (posedge clk) begin
    if ((grp_Filter_filter_fu_72_output_r_ap_vld == 1'b1)) begin
        output_r <= grp_Filter_filter_fu_72_output_r;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

endmodule //Filter
